### ISSUE TITLE
PO3 returning either SerialNumber or ID

### ISSUE THREAD

**Issue by miguelrodlav** [iHealthDeviceLabs/iHealthDeviceLabs-iOS#14]
Hi,

Quick question:

PO3 discover notification sometimes return the "ID" and sometimes "SerialNumber".

Why is this happening? Can I set this to always return the "SerialNumber"?

Thanks!

**Comment by qqskim** [comment]
For your question, you will get the id parameter only for the first time connection.  For the next time, you will get the SerialNumber.

Because we cannot get the SerialNumber for the first time connection. After the first connection,  SDK will ask the SerialNumber from PO3, then cache the relationship for the id parameter and SerialNumber. For the next time, SDK will get the SerialNumber from the cache, then back for you.
